name: build-wf
on:
  push:
    branches:
      - develop
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    permissions: 
      pages: write
      contents: read
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Welcome step
        run: echo "Allah Always Help Me"
      - name: chekcout repository
        uses: actions/checkout@v4
      - name: Install Build Tool
        run: npm install --save-dev parcel
      - name: Build Website
        # run: npx parcel ./src/index.html --dist-dir dev_build
        run: npx parcel build ./src/index.html --dist-dir ./dev
      - name: Check dev_build Folder
        run: |
          cd dev
          ls -l                    
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./dev
      - name: Deployment to to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{github.token}}
