name: build-wf
on:
  push:
    branches:
      - develop
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    permissions: 
      pages: write
      contents: read
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Welcome step
        run: echo "Allah Always Help Me"
      - name: chekcout repository
        uses: actions/checkout@v4
      - name: Install Build Tool
        run: npm install --save-dev parcel
      - name: Build Website
        # run: npx parcel ./src/index.html --dist-dir dev_build
        run: npx parcel build ./src/index.html --dist-dir dev_build
      - name: Check dev_build Folder
        run: |
          cd dev_build
          ls -l
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: ./dev_build
      - name: Deployment to to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4